# Generated by Django 3.1.1 on 2020-11-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_offer_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
