# Generated by Django 3.1.1 on 2020-12-01 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
