# Generated by Django 3.1.4 on 2020-12-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_offer_trader'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
            preserve_default=False,
        ),
    ]
