# Generated by Django 3.1.4 on 2020-12-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='isAccepted',
            field=models.BooleanField(default=False),
        ),
    ]
